### Order Service Health Check
GET http://localhost:9000/health
Content-Type: application/json

### Get Cart Details
GET http://localhost:9000/cart
Content-Type: application/json

### Create Cart
POST http://localhost:9000/cart
Content-Type: application/json

{
    "productId":"0a98c22d-0344-487c-9339-001dab00c58b",
    "customerId":"fa179915-5603-4758-967c-2a150bfe3560",
    "quantity":10
}
