### Create a new product
POST http://localhost:8080/catalog/products
Content-Type: application/json

{
    "name": "iPad Air",
    "description": "smart tablet by apple",
    "price": 189.99,
    "stock": 100
}

### Get a list of products
GET http://localhost:8080/catalog/products?limit=10&offset=0
Content-Type: application/json

### Get a single product by id
GET http://localhost:8080/catalog/products/0a98c22d-0344-487c-9339-001dab00c58b
Content-Type: application/json

### delete an existing product
DELETE http://localhost:8080/catalog/products/0a98c22d-0344-487c-9339-001dab00c58b
Content-Type: application/json

### update an existing product
PATCH  http://localhost:8080/catalog/products/0a98c22d-0344-487c-9339-001dab00c58b
Content-Type: application/json

{
    "name": "iPhone 16",
    "description": "smart phone by apple",
    "price": 199.99,
    "stock": 100
}